# Site settings
title: Meus posts
email: your-email@domain.com
lang: pt-BR
description: >- # this means to ignore newlines until "baseurl:"
  rlaunemacedo. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/posts" # the subpath of your site, e.g. /blog/
url: https://rlaunemacedo.github.io # the base hostname & protocol for your site
git_address: https://github.com/rlaunemacedo/posts
git_edit_address: https://github.com/rlaunemacedo/posts/_posts
links: 
  - label: "Twitter"
    icon: "fa fa-twitter-square"
    # url:
  - label: "Facebook"
    icon: "fa fa-facebook-square"
    url: https://www.facebook.com/rnlaune.macedo
  - label: "GitHub"
    icon: "fa fa-github"
    url: https://github.com/rlaunemacedo/
  - label: "GitLab"
    icon: "fa fa-gitlab"
    # url:
  - label: "Bitbucket"
    icon: "fa fa-bitbucket"
    # url:
  - label: "Instagram"
    icon: "fa fa-instagram"
    url: https://www.instagram.com/rlaunemacedo/




# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: flatly # ****yeti united **superhero spacelab solar slate simplex sandstone readable lumen journal  **darkly *cyborg custom ***cosmo cerulean paper

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: America/Fortaleza
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

